channels:
  - ome
  - ilastik-forge
  - ilastik-forge/label/ilastik133
dependencies:
  - numba==0.48.0
  - omero-py  # ome
  - pip
  # ilastik
  - greenlet
  - grpcio
  - h5py
  - psutil
  - tifffile
  - scikit-image<=0.16
  - scikit-learn
  - yapsy
  - vigra
  - z5py
  - elf==0.2.1.post7  # ilastik-forge
  - fastfilters==0.2.6.post26  # ilastik-forge
  - hytra==1.1.4.post66 # ilastik-forge
  - ilastikrag==0.1.3.post38 # ilastik-forge
  - ilastiktools==0.2.post32 # ilastik-forge
  - ilastik-feature-selection  # ilastik-forge
  - ilastik-meta==1.4.0b5  # ilastik-forge
  - mamutexport==0.2.1.post5  # ilastik-forge
  - ndstructs==0.0.1dev1  # ilastik-forge
  - tiktorch==20.7.1  # ilastik-forge
  - pip:
    - itkwidgets
    - ome-zarr
