channels:
  - anaconda
  - conda-forge
  - ilastik-forge
  - ome
dependencies:
  - numba==0.48.0
  - omero-py  # ome
  - pip
  - ipywidgets
  # ilastik
  - h5py<3.2
  - ilastik-dependencies-no-solvers==1.4.3
  - ilastik-forge/label/ilastik140::ilastik-meta==1.4.0b14  # ilastik-forge
  - pip:
    - yapsy
    - itkwidgets
    - ome-zarr
