channels:
  - ome
  - anaconda
  - conda-forge
  - ilastik-forge
  - ilastik-forge/label/ilastik133
dependencies:
  - numba==0.48.0
  - xarray
  - omero-py  # ome
  - pip
  # ilastik
  - greenlet
  - grpcio
  - h5py<3.2
  - psutil
  - tifffile
  - scikit-image
  - scikit-learn
  - vigra
  - z5py
  - elf  # ilastik-forge
  - fastfilters  # ilastik-forge
  - hytra # ilastik-forge
  - ilastikrag # ilastik-forge
  - ilastiktools # ilastik-forge
  - ilastik-feature-selection  # ilastik-forge
  - ilastik-forge/label/ilastik140::ilastik-meta  # ilastik-forge
  - mamutexport  # ilastik-forge
  - ndstructs  # ilastik-forge
  - tiktorch  # ilastik-forge
  - pip:
    - yapsy
    - itkwidgets
    - ome-zarr
